### ISSUE TITLE
Error `Path must be a string. Received null`

### ISSUE THREAD

**Issue by opes** [kisstkondoros/gutter-preview#17]
Hello!

I am getting a repeated occurrence of the following error:

```javascript
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at Object.map (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:97:38)
    at absoluteUrlMappers.map.mapper (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:150:76)
    at Array.map (<anonymous>)
    at recognizedImages.forEach (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:150:55)
    at Array.forEach (<anonymous>)
    at collectEntries (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:149:30)
    at scan (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:278:13)
    at Timeout.setTimeout [as _onTimeout] (/Users/admin/.vscode-insiders/extensions/kisstkondoros.vscode-gutter-preview-0.13.0/out/src/extension.js:271:39)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Running Code - Insiders, Version 1.26.0-insider, macOS 10.13.6

The error has been intermittent, so I haven't been able to nail down solid repro steps for it just yet, but I thought I would submit this issue in the meantime.

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem, I've just released version 0.13.1 to fix this. :fireworks:

**Comment by opes** [comment]
Oh wow, that was fast! Awesome, thank you!

**Comment by kisstkondoros** [comment]
I like to have 0 bugs in my repos. ^^
