### ISSUE TITLE
Previews not displaying (Cannot convert undefined or null to object: TypeError)

### ISSUE THREAD

**Issue by FelesNoctis** [kisstkondoros/gutter-preview#39]
Since the update to **0.17.3** it appears that, at least on my end, the extension has stopped functioning altogether despite being enabled. When I pull open the developer console to try and catch a glimpse, the below is sitting in the console. Downgrading back to **0.17.2** has enabled functionality again.

EDIT:
I'm seeing one of the lines from Issue #38 in there, the `Timeout.throttleIds` line from `decorator.js:19:17`, unsure if that's relevant?

Dev Console Log:
```
/C:/Users/bwfan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1536
ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at symbolUpdater (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\extension.js:95:28)
    at scan (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\decorator.js:138:13)
    at Timeout.throttleIds.(anonymous function).setTimeout [as _onTimeout] (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\decorator.js:19:17)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

log.ts:173
ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at symbolUpdater (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\extension.js:95:28)
    at scan (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\decorator.js:138:13)
    at Timeout.throttleIds.(anonymous function).setTimeout [as _onTimeout] (C:\Users\bwfan\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.17.3\out\src\decorator.js:19:17)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by BartolomeSintes** [comment]
I have the same problem. 0.17.3 does not display the image nor show the image size in VSCode 1.31.1 in windows 7, but rolling back to 0.17.2 restores the functionality. I could provide any additional information that can help you to solve this issue.

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem, I really hope that the new version 0.17.4 will resolve this issue eventually, sorry for the inconvenience.

**Comment by BartolomeSintes** [comment]
Works OK now. Thank you very much!

**Comment by FelesNoctis** [comment]
Can confirm it's also working in my environment, thank you!
