### ISSUE TITLE
启用image preview后输出报错

### ISSUE THREAD

**Issue by Oneideals** [kisstkondoros/gutter-preview#64]
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:114:13)
    at request (http.js:41:10)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:33897
    at new Promise (<anonymous>)
    at Module.V [as default] (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:32649)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84383
    at new Promise (<anonymous>)
    at Object.store (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84303)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:144279
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:142097
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 下午1:36:23] (node:1304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:114:13)
    at request (http.js:41:10)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:33897
    at new Promise (<anonymous>)
    at Module.V [as default] (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:32649)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84383
    at new Promise (<anonymous>)
    at Object.store (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84303)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:144279
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:142097
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:114:13)
    at request (http.js:41:10)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:33897
    at new Promise (<anonymous>)
    at Module.V [as default] (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:9:32649)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84383
    at new Promise (<anonymous>)
    at Object.store (c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:84303)
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:144279
    at c:\Users\cheng\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.22.2\dist\server.js:1:142097
[Error - 下午1:36:23] (node:1304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by kisstkondoros** [comment]
Thanks for the issue report, v0.22.3 was just published which should fix this by encoding utf-8 characters in URIs.

Related: https://github.com/bitinn/node-fetch/issues/531
